### ISSUE TITLE
Base de datos 

### ISSUE THREAD

**Issue by Libardo06** [4SoftwareDevelopers/demo-crud-spring-boot#2]
Deberías compartir un Script basico de la base de datos para que al menos se pueda hacer una conexion

**Comment by 4SoftwareDevelopers** [comment]
Son solo dos tablas con 4 campos, el script de la tabla persona, está aquí:
https://gist.github.com/4SoftwareDevelopers/c964b0f45903dab860609df24100e03c

**Comment by 4SoftwareDevelopers** [comment]
Son solo dos tablas con 4 campos, el script de la tabla persona, está aquí:
https://gist.github.com/4SoftwareDevelopers/c964b0f45903dab860609df24100e03c
